services:
  - type: web
    name: duolingo-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PROJECT_NAME
        value: Duolingo Clone API
      - key: API_V1_STR
        value: /api
      - key: SQLITE_URL
        value: sqlite:///./duolingo.db
      - key: FRONTEND_URL
        value: https://duolingo-app-jet.vercel.app